# 代价地图通用参数配置

# 坐标系和机器人参数
robot_radius: 0.2  # 如果使用footprint参数，此参数将被忽略
# footprint: [[x0, y0], [x1, y1], ... [xn, yn]]  # 机器人轮廓多边形

# 障碍物检测参数
obstacle_range: 2.5  # 加入代价地图的最大障碍物范围
raytrace_range: 3.0  # 清除代价地图区域的最大范围

# 传感器数据来源
observation_sources: laser_scan_sensor

laser_scan_sensor: {
  sensor_frame: laser,
  data_type: LaserScan, 
  topic: /scan,
  marking: true, 
  clearing: true,
  max_obstacle_height: 0.4,
  min_obstacle_height: 0.0,
  obstacle_range: 2.5,
  raytrace_range: 3.0
}

# 膨胀参数
inflation_radius: 0.3  # 机器人周围膨胀的距离
cost_scaling_factor: 10.0  # 影响膨胀区域的代价值计算（越高，代价衰减越快）