# Target Parameters
TARGET_VELOCITY: 0.3 # [m/s]  # 期望速度

# Simulation Parameters
PREDICT_TIME: 3.0     # [s]   # 预测未来时间长度
SIM_TIME_SAMPLES: 10          # 每条轨迹内采样点数
SIM_PERIOD: 0.1       # [s]   # 每个采样点之间的间隔时间
SIM_DIRECTION: 1.57   # [rad] # 模拟朝向
SLOW_VELOCITY_TH: 0.1 # [m/s] # 判定为“慢速”时的阈值
VELOCITY_SAMPLES: 6           # 不同线速度候选数量 #3
YAWRATE_SAMPLES: 30           # 不同角速度候选数量 #20

# Cost Parameters
OBSTACLE_COST_GAIN: 0.7 # 越大越远离障碍
TO_GOAL_COST_GAIN: 1.0  # 越大越朝向目标
USE_PATH_COST: True
SPEED_COST_GAIN: 0.4    # If path cost is used, setting the param "SPEED_COST_GAIN" to a value close to the param "PATH_COST_GAIN" may indicate better behavior
PATH_COST_GAIN: 0.4     # If path cost is used, set the param "USE_PATH_COST" to true
ANGLE_RESOLUTION: 0.087 # [rad] # 每个角度分辨率 (约 5°)
OBS_RANGE: 2.5          # [m]   # 用于考虑障碍物的范围（越大越保守）

# Goal Tolerance Parameters
GOAL_THRESHOLD: 0.1           # [m]
TURN_DIRECTION_THRESHOLD: 10    #0.1 # [rad]

# Other Parameters
ANGLE_TO_GOAL_TH: pi # [rad]